#!/bin/sh
# setup-harness-kit.sh — wire harness-kit skills into a consumer repo.
#
# Run from the CONSUMER REPO ROOT, after adding harness-kit as a submodule:
#
#   git submodule add <harness-kit-url> harness-kit
#   git submodule update --init --recursive
#   ./harness-kit/scripts/setup-harness-kit.sh
#
# Creates SYMLINKS ONLY. Skills stay canonical in the submodule, so a kit upgrade
# is a submodule pointer bump plus a re-run of this script — never a per-repo edit.
#
# Idempotent: running twice changes nothing. Refuses to touch anything it did not
# generate (guarded by the .harness-kit-merge marker).
set -eu

KIT_DIR_NAME=harness-kit
MERGE_DIR=.agents/skills
MARKER="$MERGE_DIR/.harness-kit-merge"

kit=$(cd "$(dirname "$0")/.." && pwd)
root=$(git -C "$kit" rev-parse --show-superproject-working-tree 2>/dev/null || true)
[ -n "$root" ] || root=$(git rev-parse --show-toplevel 2>/dev/null || true)

if [ -z "$root" ]; then
  echo "error: not inside a git repository. Run from the consumer repo root." >&2
  exit 1
fi
if [ "$root" = "$kit" ]; then
  echo "error: this is the harness-kit repo itself. Run it from the consumer repo root," >&2
  echo "       e.g. ./$KIT_DIR_NAME/scripts/setup-harness-kit.sh" >&2
  exit 1
fi

cd "$root"
rel=${kit#"$root"/}

# --- merge directory of per-skill symlinks -----------------------------------
if [ -e "$MERGE_DIR" ] && [ ! -e "$MARKER" ]; then
  echo "error: $MERGE_DIR exists but was not generated by this script." >&2
  echo "       Move any hand-authored skills to .agents/local-skills/ and re-run." >&2
  exit 1
fi

mkdir -p "$MERGE_DIR"
printf '%s\n' "generated by $KIT_DIR_NAME/scripts/setup-harness-kit.sh — do not hand-edit" > "$MARKER"

# Drop stale kit symlinks so removed skills do not linger; leave everything else.
for entry in "$MERGE_DIR"/*; do
  [ -L "$entry" ] || continue
  case "$(readlink "$entry")" in *"$KIT_DIR_NAME"/skills/*) rm -f "$entry" ;; esac
done

count=0
for skill in "$kit"/skills/*/; do
  name=$(basename "$skill")
  case "$name" in .*) continue ;; esac          # skip .harness working state
  [ -f "$skill/SKILL.md" ] || continue
  ln -sfn "../../$rel/skills/$name" "$MERGE_DIR/$name"
  count=$((count + 1))
done

# --- project-local skills win on name collision ------------------------------
if [ -d .agents/local-skills ]; then
  for skill in .agents/local-skills/*/; do
    [ -d "$skill" ] || continue
    name=$(basename "$skill")
    ln -sfn "../local-skills/$name" "$MERGE_DIR/$name"
  done
fi

# --- tool paths: only wire what this repo already uses ------------------------
for tool in .claude .cursor; do
  [ -d "$tool" ] || continue
  if [ -e "$tool/skills" ] && [ ! -L "$tool/skills" ]; then
    echo "warn: $tool/skills exists and is not a symlink — leaving it alone." >&2
    continue
  fi
  ln -sfn "../$MERGE_DIR" "$tool/skills"
done

# --- gitignore the working directory -----------------------------------------
if [ -f .gitignore ] && ! grep -qx 'skills/.harness/' .gitignore; then
  printf '\n# harness working state — contracts, local templates, session state\nskills/.harness/\n' >> .gitignore
fi

echo "harness-kit: linked $count skills into $MERGE_DIR"
echo "  upgrade: git submodule update --remote $rel && ./$rel/scripts/setup-harness-kit.sh"
